# Generated by Django 2.2.1 on 2019-06-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0003_auto_20190120_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='chinook.Genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='chinook.MediaType'),
        ),
        migrations.AddField(
            model_name='genre',
            name='media_types',
            field=models.ManyToManyField(related_name='genres', through='chinook.Album', to='chinook.MediaType'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='chinook.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='chinook.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='chinook.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='chinook.MediaType'),
        ),
    ]
